apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payments-saga-kv
spec:
  provider: azure
  secretObjects:
    - secretName: payments-saga-secrets
      type: Opaque
      data:
        - objectName: db-url
          key: db-url
        - objectName: db-user
          key: db-user
        - objectName: db-pass
          key: db-pass
        - objectName: jwt-secret
          key: jwt-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<managed-identity-client-id>"
    keyvaultName: "<key-vault-name>"
    cloudName: ""
    tenantId: "<azure-tenant-id>"
    objects: |
      array:
        - |
          objectName: db-url
          objectType: secret
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-pass
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
