apiVersion: v1
kind: Service
metadata:
  name: payments-saga
  labels:
    app: payments-saga
spec:
  type: ClusterIP
  selector:
    app: payments-saga
  ports:
    - name: http
      port: 80
      targetPort: 8080
